# Generated by Django 4.2.16 on 2024-09-21 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Stadium', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_matches', models.CharField(max_length=200)),
                ('away_matches', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('default_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stadium.stadium')),
            ],
        ),
    ]
